interactions:
- request:
    body: !!binary |
      eyJ1c2VybmFtZSI6ICJkZXYiLCAibmV4dCI6ICJodHRwOi8vbG9jYWxob3N0Ojg5MDEvYXBpLyIs
      ICJwYXNzd29yZCI6ICJpbnZhbGlkIn0=
    headers:
      Accept: ['*/*']
      Accept-Encoding: ['gzip, deflate']
      Connection: [keep-alive]
      Content-Length: ['80']
      Content-Type: [application/json; charset=UTF-8]
      Referer: ['http://localhost:8901/api/token-auth/']
      User-Agent: [python-requests/2.6.2 CPython/3.4.3 Linux/3.16.0-38-generic]
    method: POST
    uri: http://localhost:8901/api/token-auth/
  response:
    body: {string: '{"non_field_errors":["Unable to login with provided credentials."]}'}
    headers:
      Allow: ['POST, OPTIONS']
      Connection: [close]
      Content-Type: [application/json]
      Date: ['Fri, 27 Nov 2015 17:19:40 GMT']
      Server: [Werkzeug/0.10.4 Python/3.4.3]
      Vary: [Accept]
      X-Frame-Options: [SAMEORIGIN]
    status: {code: 400, message: BAD REQUEST}
version: 1
